import Head from 'next/head';
import Navbar from "../components/navbar/navbar"
import Search from "../components/search/search"
import MainContainer from "../components/maincontainer/maincontainer"
import Footer from "../components/footer/footer"


export default function Home() {
  return (
    <>
      <Head>
        <title>Easter Eggs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="bg-[#5e503f] text-[#edf2f4] font-poppins">
        <Navbar />
        <Search />
        <MainContainer />
        <Footer />
      </main>
    </>
  )
}
